name: backend
services:
    backend:
        build: 
            context: ./server
        container_name: server-app
        networks:
            - mynetwork
        ports:
            - 5000:5000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    db:
        container_name: madcinema-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Rachenok_1111
        ports:
            - 1433:1433
        networks:
            - mynetwork
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    mynetwork:
        driver: bridge
